version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
  redis:
    image: redis:3.2
    ports:
      - "16379:6379"
  app:
    image: user-details-poc
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_DRIVER: redis
    extra_hosts:
      - "soci.al:127.0.0.1"
    ports:
      - "8080:80"
    volumes:
      - .:/opt/user-details-poc
  proxy:
    image: shopify/toxiproxy
    volumes:
      - ./.docker:/etc/user-details-poc
    command: ["-config=/etc/user-details-poc/toxiproxy.json", "-host=0.0.0.0"]
    ports:
      - "18474:8474"
